version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: container-loja
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: moro1667
      POSTGRES_DB: sistema-loja
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: sistema-loja
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

volumes:
  pgdata: